### ISSUE TITLE
about the SNA parameter estimation

### ISSUE THREAD

**Issue by fm123a** [megvii-research/PMN#1]
hi, The parameters of the Gaussian distribution (mean,std)  is selected randomly or calibrated by some raw image about SNA in the paper? there are some questions about them .

**Comment by fenghansen** [comment]
All noise model parameters are calibrated using the calibration method provided by [ELD](https://github.com/Vandermode/ELD), which is recorded in `data_process/process.py#L354`.
SNA does not actually use the parameters of Gaussian distribution. The 'else' branch left over from the exploratory experiment that was not deleted. I recently found out that this part may be called due to some mistakes in my cleanup process, I will fix it later.

**Comment by fm123a** [comment]
1. in get_aug_param_torch demo, why you set the parameter value  r to 0.25 or 0.5 (np.random.randint(2) * 0.25 + 0.25)?,  is the r chosen by random setting or by calibration?
2.  By doing the clip operation， aug_r>0,  aug_g>0,aug_b >0, Why do the following operations：
daug = -np.minimum(np.min(aug_wb), 0)
        if daug == 0:
            # 只有增益的话很好处理，叠加泊松分布就行
            dy = gt * aug_wb.reshape(-1,1,1)    # 我考虑过这里dy和dn要不要量化一下，感觉不量化对多样性更友好
            dn = np.random.poisson(dy/p['K']).astype(np.float32) * p['K']
        else:
            # 存在减益的话就很麻烦，需要考虑read noise并且补齐分布
            scale = 1 - daug

**Comment by fenghansen** [comment]
1. random setting (Intuition. I think it may be better.)
2. This is the BiSNA I forgot to remove and I will describe it in future work. BiSNA needs to be used with a special augmentation. This branch is not released and will not be called.
