### ISSUE TITLE
unmachted checkpoint

### ISSUE THREAD

**Issue by xiaobiaodu** [megvii-research/PMN#3]
Hi

I use your instruction to test your code. But I meet the following problem.
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Unexpected key(s) in state_dict: "conv1_1.weight", "conv1_1.bias", "conv1_2.weight", "conv1_2.bias", "conv2_1.weight", "conv2_1.bias", "conv2_2.weight", "conv2_2.bias", "conv3_1.weight", "conv3_1.bias", "conv3_2.weight", "conv3_2.bias", "conv4_1.weight", "conv4_1.bias", "conv4_2.weight", "conv4_2.bias", "conv5_1.weight", "conv5_1.bias", "conv5_2.weight", "conv5_2.bias", "upv6.weight", "upv6.bias", "conv6_1.weight", "conv6_1.bias", "conv6_2.weight", "conv6_2.bias", "upv7.weight", "upv7.bias", "conv7_1.weight", "conv7_1.bias", "conv7_2.weight", "conv7_2.bias", "upv8.weight", "upv8.bias", "conv8_1.weight", "conv8_1.bias", "conv8_2.weight", "conv8_2.bias", "upv9.weight", "upv9.bias", "conv9_1.weight", "conv9_1.bias", "conv9_2.weight", "conv9_2.bias", "conv10_1.weight", "conv10_1.bias".

It seems the checkpoint is unmatched by your model,  could you please fix it?

**Comment by fenghansen** [comment]
Oh I think I know where the problem is.
I'll make a fix and update the code this week. If you are in a hurry to verify, you only need to change the `Line 471` in `trainer_SID.py` to `trainer.net = load_weights(trainer.net, best_model, multi_gpu=trainer.multi_gpu)`.
This project only needs to run on a single card, thus I didn't test the multi_gpu branch. It is recommended to use a single card to run the code, which is completely sufficient and more stable.

**Comment by xiaobiaodu** [comment]
Good Job!
